version: '3.8'

services:
  pocketai:  # 使用应用名称作为服务名
    build: .
    restart: always
    volumes:
      - ./:/app
      - ./db.sqlite3:/app/db.sqlite3  # 直接映射本地数据库文件
      - ./staticfiles:/app/staticfiles  # 项目静态文件
      - ./media:/app/media  # 媒体文件
      # 映射到宿主机的特定目录，方便nginx配置
      - /var/www/static/pocketai:/app/staticfiles
      - /var/www/media/pocketai:/app/media
    ports:
      - "8002:8002"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - STATIC_URL=/static/pocketai/  # 注意这里使用了应用特定的路径
      - MEDIA_URL=/media/pocketai/
      - TIME_ZONE=Asia/Shanghai