# Generated by Django 3.2.25 on 2025-03-11 12:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='基金名称')),
                ('user_id', models.CharField(db_index=True, max_length=50, verbose_name='用户ID')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='目标金额')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='当前金额')),
                ('deadline', models.DateTimeField(verbose_name='截止日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '梦想基金',
                'verbose_name_plural': '梦想基金',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='存款金额')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('deposit_date', models.DateTimeField(auto_now_add=True, verbose_name='存款日期')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='goals.goal', verbose_name='梦想基金')),
            ],
            options={
                'verbose_name': '存款记录',
                'verbose_name_plural': '存款记录',
                'ordering': ['-deposit_date'],
            },
        ),
    ]
