# Generated by Django 3.2.25 on 2025-03-11 18:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='用户ID')),
                ('model', models.CharField(max_length=255, verbose_name='模型名称')),
                ('assistant_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='助手名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '消息会话',
                'verbose_name_plural': '消息会话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='用户ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('transaction_ids', models.TextField(default='0', help_text='以逗号分隔的交易ID列表，默认为0表示无关联交易', verbose_name='关联交易ID')),
                ('random_seed', models.CharField(default=uuid.uuid4, help_text='用于消息的唯一性标识', max_length=36, verbose_name='随机种子')),
                ('message_type', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], db_index=True, default='user', max_length=20, verbose_name='消息类型')),
                ('is_user', models.BooleanField(default=True, help_text='已废弃，请使用message_type字段', verbose_name='是否用户消息')),
                ('is_voice', models.BooleanField(default=False, verbose_name='是否语音消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to='ai_messages.messagesession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['created_at'],
            },
        ),
    ]
