# Generated by Django 3.2.25 on 2025-03-11 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='random_seed',
        ),
        migrations.AddField(
            model_name='message',
            name='random',
            field=models.IntegerField(default=0, verbose_name='随机种子'),
        ),
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_messages.messagesession', verbose_name='所属会话'),
        ),
    ]
