# Generated by Django 3.2.25 on 2025-03-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_messages', '0002_auto_20250312_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='emoji',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='表情字段'),
        ),
    ]
