# Generated by Django 3.2.25 on 2025-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_messages', '0003_message_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='emoji',
            field=models.CharField(default='random', max_length=50, verbose_name='表情字段'),
        ),
    ]
