# Generated by Django 3.2.25 on 2025-03-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_messages', '0004_alter_message_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='语音路径'),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='语音秒数'),
        ),
    ]
