# Generated by Django 3.2.25 on 2025-03-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='账本名称')),
                ('user_id', models.IntegerField(db_index=True, help_text='UserCenter的用户ID', verbose_name='用户ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认账本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledgers', to='categorization.ledgercategory', verbose_name='账本分类')),
            ],
            options={
                'verbose_name': '账本',
                'verbose_name_plural': '账本',
                'ordering': ['-is_default', 'name'],
                'unique_together': {('user_id', 'name')},
            },
        ),
    ]
