# Generated by Django 3.2.25 on 2025-03-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', '美元'), ('CNY', '人民币'), ('EUR', '欧元'), ('JPY', '日元'), ('KRW', '韩元')], max_length=3, unique=True, verbose_name='货币代码')),
                ('rate_to_usd', models.DecimalField(decimal_places=6, help_text='1单位该货币等于多少美元', max_digits=15, verbose_name='兑美元汇率')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '货币汇率',
                'verbose_name_plural': '货币汇率',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资产名称')),
                ('currency', models.CharField(choices=[('USD', '美元'), ('CNY', '人民币'), ('EUR', '欧元'), ('JPY', '日元'), ('KRW', '韩元')], default='USD', max_length=3, verbose_name='货币类型')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='资产余额')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('include_in_total', models.BooleanField(default=True, help_text='是否将此资产计入总资产', verbose_name='列入总资产计算')),
                ('user_id', models.CharField(db_index=True, max_length=50, verbose_name='用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='categorization.assetcategory', verbose_name='资产分类')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'ordering': ['-balance', 'name'],
            },
        ),
    ]
