# Generated by Django 5.1.6 on 2025-03-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='图标')),
                ('category_type', models.CharField(choices=[('debit', '借记卡/现金'), ('credit', '信用卡'), ('borrow_lend', '借贷'), ('investment', '投资')], max_length=20, verbose_name='资产大分类')),
                ('is_positive_asset', models.BooleanField(default=True, verbose_name='是否正资产')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小排序越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产分类',
                'verbose_name_plural': '资产分类',
                'ordering': ['sort_order', 'category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='图标')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认账本')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小排序越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '账本分类',
                'verbose_name_plural': '账本分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('is_income', models.BooleanField(default=False, help_text='默认为支出', verbose_name='是否收入')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小排序越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '交易分类',
                'verbose_name_plural': '交易分类',
                'ordering': ['sort_order', '-is_income', 'name'],
            },
        ),
    ]
