# Generated by Django 3.2.25 on 2025-03-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0002_alter_assetcategory_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='category_type',
            field=models.CharField(choices=[('借记卡/现金', '借记卡/现金'), ('信用卡', '信用卡'), ('借贷', '借贷'), ('投资', '投资'), ('网络', '网络')], max_length=20, verbose_name='资产大分类'),
        ),
    ]
