# Generated by Django 3.2.25 on 2025-03-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('ledger', '0001_initial'),
        ('categorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=50, verbose_name='用户ID')),
                ('is_expense', models.BooleanField(default=True, help_text='默认为支出，否则为收入', verbose_name='是否支出')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='交易金额')),
                ('transaction_date', models.DateTimeField(db_index=True, verbose_name='交易时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('include_in_stats', models.BooleanField(default=True, verbose_name='纳入统计')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='assets.asset', verbose_name='关联资产')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categorization.transactioncategory', verbose_name='交易分类')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger.ledger', verbose_name='所属账本')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user_id', 'transaction_date'], name='transaction_user_id_e55ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['ledger', 'transaction_date'], name='transaction_ledger__942a16_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['asset', 'transaction_date'], name='transaction_asset_i_5e8e5c_idx'),
        ),
    ]
